<?php

namespace AdminBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $record
     * @return array|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneUser($record)
    {
        return $this->getEntityManager()
            ->createQuery("
                SELECT u.id,
                       u.username,
                       u.email,
                       u.isActive
                  FROM AdminBundle:User u
                 WHERE u.id = :id
            ")
            ->setParameter('id', $record)
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }

    /**
     * @param string $username
     * @param int $record
     * @return array|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findUniqueUser($username, $record)
    {
        return $this->getEntityManager()
            ->createQuery("
                SELECT 1
                  FROM AdminBundle:User u
                 WHERE u.username = :username
                   AND u.id != :id
            ")
            ->setParameter('username', $username)
            ->setParameter('id', $record)
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }

    /**
     * @param int $deleted
     * @return array
     */
    public function findListUser($deleted = 0)
    {
        return $this->getEntityManager()
            ->createQuery("
                SELECT u.id,
                       u.username,
                       u.email,
                       u.isActive
                  FROM AdminBundle:User u
                 WHERE u.deleted = :deleted
            ")
            ->setParameter('deleted', $deleted)
            ->getResult();
    }
}
