home:
    path:     /
    defaults: { _controller: AdminHome:Home:index }
_navbar:
    path:     /navbar/top
    defaults: { _controller: AdminHome:Navbar:top }

_user_form:
    path:     /user/form/{record}
    defaults: { _controller: AdminHome:User:form, record: -1 }

_user_list:
    path:     /user/list/{page}
    defaults: { _controller: AdminHome:User:list, page: 1 }

_user_save:
    path:     /user/save
    defaults: { _controller: AdminHome:User:save }

_user_update:
    path:     /user/update/{record}
    defaults: { _controller: AdminHome:User:update, record: -1 }