AdminBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
    getters:
        passwordLegal:
            - 'IsTrue': { message: 'The password cannot match your first name.' }
        passwordConfirm:
            - 'IsTrue': { message: 'Passwords are not the same.' }
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 3
        password:
            - NotBlank: ~
            - Length:
                min: 5
        email:
            - NotBlank: ~
            - Length:
                min: 3

AdminBundle\Entity\Role:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: role
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
        role:
            - NotBlank: ~
            - Length:
                min: 6