AdminBundle\Entity\User:
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 3
        password:
            - NotBlank: ~
            - Length:
                min: 3
        email:
            - NotBlank: ~
            - Length:
                min: 3