# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    superadmin: { password: 3lKE6EZYz8XrKhrsrFBpq7rdPWNkxkUugXnfV+v8Il1ZEDFe3wiZFH6DEYMDd9cyIYzC74DswFFqonNgbc4BPw==, roles: ['ROLE_SUPER_ADMIN'] }
        user_db:
            entity:
                class: AdminBundle:User
                property: username
    encoders:
        AdminBundle\Entity\User: sha512
        Symfony\Component\Security\Core\User\User: sha512

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            provider: user_db
            anonymous: ~
            http_basic:
                realm: 'Secured Demo Area'
                provider: in_memory
            form_login:
                login_path: _security_login
                check_path: _security_login
                default_target_path: _admin

            logout:
                path:   _logout
                target: _security_login
            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    role_hierarchy:
        ROLE_USER:        [IS_AUTHENTICATED_ANONYMOUSLY]
        ROLE_AUTHOR:      [ROLE_USER]
        ROLE_MODERATOR:   [ROLE_AUTHOR]
        ROLE_ADMIN:       [ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
