# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        db_provider:
            entity:
                class: AdminBundle:User
                property: username
    encoders:
        AdminBundle\Entity\User:
            algorithm: bcrypt
            cost:      15

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            provider: db_provider
            anonymous: ~

            form_login:
                login_path: _security_login
                check_path: _security_login
                default_target_path: _admin

            logout:
                path:   _logout
                target: _security_login
            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY }